### ISSUE TITLE
Prompt for kibana path

### ISSUE THREAD

**Issue by w33ble** [elastic/generator-kibana-plugin#10]
We [hard-code this now](https://github.com/elastic/generator-kibana-plugin/blob/59003e65fca6c3f76f49630ca2364e012a1d16c0/generators/app/templates/gulpfile.js#L22), but we should lean on yeoman prompts for it. This would also allow us to confirm that the path exists, and perhaps even verify that it's where Kibana is currently installed.

**Comment by petmakris** [comment]
+1

At least it should be explained better in the README what "the same level" is

**Comment by w33ble** [comment]
@petmakris updating the README is easy enough. I'm not sure how to be more clear about what we mean though - any suggestion for how to word that better?

**Comment by Kikketer** [comment]
"At the same level" didn't mean much to me either since I didn't have my cloned development environment named "kibana".  So I second the ability to alter the hardcoded location of kibana.
Pictures say a thousand words, even ascii :)

```
<parent dir>
  |- kibana
  |- your-plugin
```

I tried three different places:  in the plugins directory inside kibana, sharing the same parent as kibana (right spot but name issue), and directly inside kibana.  All failed and I was upset... I then started searching for what "plugin-helpers" was and where it was intending to look.  I found it here.

**Comment by w33ble** [comment]
The template asks for the location if it doesn't find it where it expects to. Unlikely to be added to the generator.
