### ISSUE TITLE
Option to generate plugin for stable version of Kibana

### ISSUE THREAD

**Issue by ifonefox** [elastic/generator-kibana-plugin#34]
Is there an option to create a plugin that works on the current stable Kibana version (4.5.3)? As far as I can tell, this only supports the unstable version.

**Comment by CCoffie** [comment]
So after a bunch of troubleshooting I was able to get a plugin generated by this generator to work with stable versions of Kibana. Figured I'd share what I did so that others might be able to replicate the process while we wait for the generator to gain this functionality.

First you'll want to add the following to you app section of your uiExports.

```
injectVars: function (server, options) {
    var config = server.config();
    return {
        kbnIndex: config.get('kibana.index'),
        esShardTimeout: config.get('elasticsearch.shardTimeout'),
        esApiVersion: config.get('elasticsearch.apiVersion')
    };
},
```

Then if you're using the config section you'll also need to import joi. Just put the following line into your export section.

```
let Joi = require('joi');
```

You will also want to do something like the following to only get `require('ui/autoload/all');` to run when you're running a newer version of kibana.

```
var mainFile = 'plugins/pluginName/app';

var ownDescriptor = Object.getOwnPropertyDescriptor(kibana, 'autoload');
var protoDescriptor = Object.getOwnPropertyDescriptor(kibana.constructor.prototype, 'autoload');
var descriptor = ownDescriptor || protoDescriptor || {};
if (descriptor.get) {
  // the autoload list has been replaced with a getter that complains about
  // improper access, bypass that getter by seeing if it is defined
  mainFile = 'plugins/pluginName/app-autoload';
}
```

You'll then want within you app section to include the line `main: mainFile`. And you're `app-autoload.js` file will look like the following:

```
require('ui/autoload/all');
require('./app');
```

That should be it. I also did have problems with not all of my node_modules being included in my build although I'm not sure if that is specific to getting it to work with a older version of kibana. To fix that I had to include all of my dependencies and their dependencies within my `package.json`. I hope that helps everyone.

**Comment by spalger** [comment]
Now that Kibana 5 is out the plugins generated are up to date with Kibana, thanks! 🎩
