### ISSUE TITLE
Generated plugin does not pass version information for kibana 6.0.0

### ISSUE THREAD

**Issue by RMKD** [elastic/generator-kibana-plugin#36]
```
$ ./bin/kibana --dev
  log   [03:39:18.823] [info][listening] basePath Proxy running at https://localhost:5601/ozn
server    log   [03:39:20.800] [warning] Plugin "sample" was disabled because it expected Kibana version "0.0.0", and found "6.0.0-alpha1".
optmzr    log   [03:39:20.805] [warning] Plugin "sample" was disabled because it expected Kibana version "0.0.0", and found "6.0.0-alpha1".
```

It turns out the version it is looking for is the second field of the `package.json` file (i.e. the version of the plugin, which seems a little counter-intuitive). It can be corrected by manually inserting the kibana version but should probably be detected and auto-inserted. 

change: 

```
{
  "name": "sample",
  "version": "0.0.0", 
  ...
```

to: 

```
{
  "name": "sample",
  "version": "6.0.0-alpha1", 
  "description": "An awesome Kibana plugin",
  "main": "index.js",
  "scripts": {
    "lint": "eslint",
    "start": "plugin-helpers start",
    "test:server": "plugin-helpers test_server",
    "test:browser": "plugin-helpers test_browser",
    "build": "plugin-helpers build",
    "postinstall": "plugin-helpers postinstall"
  },
  "devDependencies": {
    "@elastic/eslint-config-kibana": "0.0.2",
    "babel-eslint": "4.1.8",
    "eslint": "1.10.3",
    "eslint-plugin-mocha": "1.1.0",
    "@elastic/plugin-helpers": "6.0.0-alpha1"
  }
}
```

**Comment by ytzlax** [comment]
Hi,
@RMKD,  But when I need to change the plugin version,it will fail again

**Comment by timroes** [comment]
@ytzlax welcome to the new kind of version hell :-)

Actually the version comparison is currently done against all three components of the semantic version (meaning major, minor and patch level must match, only a possible tag is stripped away). So basically the only thing you can change without breaking again is the tag (which is also a bit misleading in the warning it shows.

A _workaround_ you can use is placing "kibana" as a version. If you set the version to "kibana" it will always work, but since the API can actually change, your plugin still might break, so I would use this with care, but on the other hand counting up every patch level of Kibana may in my opinion also not be the way to go.

You can find the version checking in the [check_version.js](https://github.com/elastic/kibana/blob/master/src/server/plugins/check_version.js) file.

**Comment by ytzlax** [comment]
@timroes , thanks

**Comment by spalger** [comment]
Updated the generator to now ask for the target Kibana version

**Comment by ytzlax** [comment]
Great, thanks

**Comment by timroes** [comment]
@ytzlax Though closed, I recognized, that you can also specify the required kibana version inside your `package.json` as:

```
{
  "kibana": {
    "version": "x.y.z"
  }
}
```

That way you can use the version as you wish and specify the compatible version separate from that. I think it's most likely what you should do, if not a core plugin.
